[package]
name = "colors"
version = "0.1.1"
edition = "2021"

[[bin]]
edition = "2021"
name = "swatcher"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-thief = "0.2.2"
image = "0.24.6"
rgb = "0.8.36"
